name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [aarch64-darwin, x86_64-linux]
    steps:
      - uses: actions/checkout@v4
      - run: om ci run --systems "${{ matrix.system }}"
